### PR TITLE
Enable test coverage reports

### PR DESCRIPTION
**Pull request by s7eph4n**
This PR addresses enables test coverage reporting.

Before this is merged somebody should enable external code coverage on Scrutinizer. See https://scrutinizer-ci.com/docs/tools/external-code-coverage/

This PR includes:
- [ ] Update of RELEASE-NOTES.md
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
You know you can use branches on this repo instead of your own right? You do have write access

**Comment by s7eph4n** [comment]
Yes, I know. In principle. It never occurred to me though. :D 
Btw, "somebody should enable external code coverage on Scrutinizer". And that I really can't do. :P

**Comment by JeroenDeDauw** [comment]
Yes you can, you just need to update https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/.scrutinizer.yml

This needs to be added: https://github.com/wmde/Euro/blob/master/.scrutinizer.yml#L5

**Comment by JeroenDeDauw** [comment]
Might need to specify custom timeout limit to avoid timeouts if the tests here are not that fast https://github.com/wmde/Diff/blob/master/.scrutinizer.yml#L5-L6

**Comment by s7eph4n** [comment]
Abyssmal, as expected: [Code Coverage](https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticResultFormats/?branch=master)
And that already includes integration tests.

**Comment by JeroenDeDauw** [comment]
Better than most MW extensions :) Also, this number does not include the JS, which this extension has a lot of, so it is actually lower.

**Pull request merged**
