### PR TITLE
[SRF][Filtered] New view 'table' added

### PR DESCRIPTION
**Pull request by gesinn-it**
At gesinn.it, we've been working internally with a "table" view enhancement for the filtered view since a while. Our customers love it. We've polished it a bit and merged it with a recent version of SRF.

Format is tested on MW 1.25.2, SMW 2.2.2. No issues.

We'd like to contribute this back to SRF so that others can use it...

### CODE REVIEW

**Comment by mitchelln** [comment]
That's really fantastic! Thanks for the effort.

**Comment by s7eph4n** [comment]
Nice!
If somebody could give this patch a spin, that'd be great. Otherwise I'll do it next week and merge it then.

**Comment by kghbln** [comment]
I am very excited about this. Very cool stuff! @gesinn-it It will be cool if you could document this after the merge an smw.o. @JeroenDeDauw I guess this could also trigger a soonish SRF 2.3 release after merge?

**Comment by gesinn-it** [comment]
@kghbln : sure, I'll modify smw.o as soon as things are merged.

**Comment by kghbln** [comment]
:+1: And I will poke @JeroenDeDauw when time comes to update smw.o so the example will work allrighty. Very excited, I am.

**Comment by JeroenDeDauw** [comment]
@kghbln sure, we can do a 2.3 rel

**Comment by mitchelln** [comment]
Any chance we could put the quick and/or default selection filter option in before a new release Stephan?

No worries if not.


Sent by Outlook for Android





On Wed, Sep 9, 2015 at 11:27 AM -0700, "Jeroen De Dauw" <notifications@github.com> wrote:
@kghbln sure, we can do a 2.3 rel

---

**Comment by JeroenDeDauw** [comment]
I have submitted some small refactoring of this new code at https://github.com/gesinn-it/SemanticResultFormats/pull/1

**Comment by JeroenDeDauw** [comment]
+1 from my side. Ping @mwjames

**Comment by mwjames** [comment]
> Would be more happy if the code was tested of course. Ping @mwjames

Since I haven't tested nor did I look at the code, I have to excuse myself from the evaluation (or recommendation).

@s7eph4n Please merge at your discretion.

**Comment by gesinn-it** [comment]
@s7eph4n can you please have a look at this PR and merge?

**Comment by s7eph4n** [comment]
Does not work for me. :(
snapshot1
snapshot2

**Comment by s7eph4n** [comment]
@gesinn-it Could you try if #127 works for you?

It is a table view that I built for SRF 1.9 some time ago that seems to also work with SRF 2.2.
There were some issues when I tried this with 2.0 or 2.1, which is why I did not merge it to master back then, but it seems to work now. No idea what changed since then (or if I was chasing phantoms).

**Comment by gesinn-it** [comment]
@s7eph4n I can reproduce the issue that the table view is not working if multiple views are used. I'll have a look at it.

**Comment by gesinn-it** [comment]
SRF_FV_Table.php

... adding $resultArray->reset() fixed it for me:

```
protected function getCellForPropVals( SMWResultArray $resultArray, $outputmode, $columnClass ) {

                $resultArray->reset();

                $dataValues = array();
```

@s7eph4n Can you directly add this line and see if it is working for you as well?

**Comment by s7eph4n** [comment]
Looks good to me.
Now, who will add this view to http://semantic-mediawiki.org/wiki/Help:Filtered_format?  ;)

**Comment by JeroenDeDauw** [comment]
Can you update the release notes?

**Comment by gesinn-it** [comment]
@JeroenDeDauw created PR with updated rel notes

**Comment by kghbln** [comment]
And it (https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/128) was merged. :)

**Comment by kghbln** [comment]
@JeroenDeDauw Ready for SRF 2.3?

**Comment by gesinn-it** [comment]
@kghbln , @JeroenDeDauw we should have PR #126 merged before the next release...

**Comment by JeroenDeDauw** [comment]
Tracking in #129

**Comment by mwjames** [comment]
@gesinn-it Besides the docu on smw.org, it would be marvellous to have a real sound example on smw.org.

**Comment by kghbln** [comment]
This will be nice indeed. I pinged @JeroenDeDauw to update smw.o Should not take to long.

**Pull request merged**
