### PR TITLE
2.1 rel

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
I did not verify if the rel notes are complete or sensible

**Comment by kghbln** [comment]
Ooooooooooooops ..... I messed up totally since I just created a tag.

**Comment by JeroenDeDauw** [comment]
picard-facepalm

**Comment by kghbln** [comment]
That's an appropriate pic I believe.

**Comment by JeroenDeDauw** [comment]
Updated the version in here to 2.1.1. Please do not create the tag before this is merged :)

**Comment by kghbln** [comment]
No, will not do this. What's actually your or James' thing to do anyway.

**Pull request merged**
