### PR TITLE
Allow phpcodesniffer-composer-installer

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by paladox** [comment]
@gesinn-it-gea would this fix it for you?

**Comment by paladox** [comment]
this is needed anyways, I get:

> Do you trust "dealerdirect/phpcodesniffer-composer-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?]

**Comment by gesinn-it-gea** [comment]
Sounds good, didn't we have this in some other repo too recently? I remember I saw this not so long ago... :-)

**Comment by paladox** [comment]
For some reason running composer install isn't installing mediawiki semantic mediawiki?

**Comment by paladox** [comment]
> For some reason running composer install isn't installing mediawiki semantic mediawiki?

Oh was looking in the wrong place. It's in extensions/ folder.

**Comment by gesinn-it-gea** [comment]
@paladox did you see: https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/882? Maybe related

**Comment by paladox** [comment]
I get dev-master locally now Did `COMPOSER=composer.local.json composer require --no-update mediawiki/semantic-media-wiki dev-master` then `composer install`.

**Comment by paladox** [comment]
> @paladox did you see: #882? Maybe related

Yeh, that's why I did this change. Possibility that this may fix that.

**Comment by paladox** [comment]
Does this fix it for you @gesinn-it-gea ?

**Pull request merged**
