### PR TITLE
[Filtered] added "list view userparam"

### LINKED ISSUE #629: [Filtered] Add "list view userparam"
Add "list view userparam" to support SMW's `#userparam`

### PR DESCRIPTION
**Pull request by gesinn-it**
This PR is made in reference to: #629 

This PR addresses or contains:
- added "list view userparam" to support SMW's #userparam

This PR includes:
- [ ] Update of RELEASE-NOTES.md
- [x] Tests (unit/integration)
- [x] CI build passed

Fixes #629

### CODE REVIEW

**Comment by gesinn-it** [comment]
@kghbln what needs to be done with regard to documentation. Do you take care of that?

**Comment by gesinn-it** [comment]
@JeroenDeDauw @kghbln can you please have a look, if the PR can be merged.

**Comment by kghbln** [comment]
> what needs to be done with regard to documentation.

It will be cool if you could add docu.

> Do you take care of that?

I can polish if necessary.

**Comment by gesinn-it** [comment]
@kghbln I can update SMW.org and prepare the release notes.

**Pull request merged**
