### PR TITLE
integration tests for math/statistical formats

### PR DESCRIPTION
**Pull request by krabina**
This PR is made in reference to: https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/604

This PR addresses or contains:
- small spelling mistakes
- added integraton tests

This PR includes:
- [x] Tests (unit/integration)
- [ ] CI build passed

We could not test the integraton test due to our lacking test environment...

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
It's great to have some integration tests. For more thoroughly testing the code in MathFormats I strongly recommend **unit** tests.

image

Unit tests are easier to write and maintain. Plus they are way faster.

**Comment by JeroenDeDauw** [comment]
Needs rebase

**Comment by krabina** [comment]
What does that mean?

**Comment by kghbln** [comment]
> What does that mean?

This means that no merge will be done until the rebase was done. Note the conflicts.

**Comment by FlorianBreitenlacher** [comment]
Before a create a rebase i need to update the fork. Am i right?

**Comment by JeroenDeDauw** [comment]
Kinda. You need to rebase against master of this repo. You can do that directly or update master on your fork and rebase against that

**Comment by FlorianBreitenlacher** [comment]
I'm not sure if I did everything right. can i get some feedback please?

**Comment by JeroenDeDauw** [comment]
One failing test now:

> There was 1 failure:

> 1) SRF\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "math-01.json" ('/home/travis/build/SemanticMe...1.json')

**Comment by FlorianBreitenlacher** [comment]
can i change the numbers during a test? From "Example/Math/1" to "Example/Math/2".

**Comment by akuckartz** [comment]
The test logs also contain this line:
> Dependency: Mermaid as requirement is not available!

**Comment by krabina** [comment]
strange. Math formats certailny don't require mermaid and in our PR we have not introduced anything related to mermaid...

**Comment by kghbln** [comment]
> strange. Math formats certailny don't require mermaid and in our PR we have not introduced anything related to mermaid...

while math formats do not require mermaid every pull is tested against all tests available for SRF. This is why you get Mermaid, too.

**Comment by krabina** [comment]
So this means we are done here?

**Comment by FlorianBreitenlacher** [comment]
don't think so still get an error by testing math-01.json. would need some help from someone who knows well about integration tests

**Comment by kghbln** [comment]
> So this means we are done here?

Since I do not know why Mermaid is causing pain I cannot tell. The last commit a week ago was passing so there may still be an issue. Some change here causing the rest to fall apart? I rather leave this to knowledgeable people sticking around here. :)

**Comment by akuckartz** [comment]
See also #567

**Comment by JeroenDeDauw** [comment]
Sigh... would be so much easier with simple unit tests. I don't know about this custom integration test stuff James created.

```
Failed "#18 format=mode"

==== (actual) ====

<div class="mw-parser-output"><p>0

</p>

</div>

==== (StringContains expected) ====

[ 3 ]
```

If the code itself looks correct, just write a unit test for it and see if it is or not. Then you know if the code is broken or this integration test stuff.

**Comment by FlorianBreitenlacher** [comment]
i guess i finally fixed the problem with my integration tests

**Comment by krabina** [comment]
Great, good work, @FlorianBreitenlacher !!

**Comment by kghbln** [comment]
I used the opportunity of passing test to merge this. :)

**Comment by kghbln** [comment]
Thanks a ton for your stamina!

**Pull request merged**
