### PR TITLE
 SemanticResultFormats datatables upgrade (KM-A)

### PR DESCRIPTION
**Pull request by thomas-topway-it**
This PR is made in reference to: [KM-A Knowledge Management Associates](https://km-a.net/knowledge-wiki/) upgrade of SemanticResultFormats Datatables
This PR addresses or contains:

- upgrade of Datatables to 1.12.1, Buttons 2.2.3, Select 1.4.0
- fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/188
- fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/726
- fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/721 
(added parameters: pagelength and lengthmenu)
- fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/93
- (datatables) added support for basic theme 
- adds play/pause button on slideshow navigation
- adds a new result format (carousel based on [slick](https://kenwheeler.github.io/slick/))
- updates Javascript tests for Datatables format, and integration tests for Carousel format
- fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/750

### CODE REVIEW

**Comment by thomas-topway-it** [comment]
the test fails because this file tests/phpunit/Integration/JSONScript/datatables-01.json checks for the wrong theme

**Comment by krabina** [comment]
For documentation. The datatables PR includes a workaround to work with the current version of SMW. 
A future version without the workaround in SRF needs to be implemented here
[SemanticMediaWiki/res/smw/data/ext.smw.dataItem.uri.js](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/res/smw/data/ext.smw.dataItem.uri.js)
But this might affect other result formats as well, so we did not want to go there yet.
This is probably also related to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3545

**Comment by krabina** [comment]
This PR is still work in progress. Will let you know when we are finished.

**Comment by krabina** [comment]
We believe or PR is ready now for integration. We improved the datatables format, fixed serveral bugs, added a new carousel format and provide php unit tests, json integration tests, and js QUnit tests.
We have tested on several production wikis on 1.35.
@JeroenDeDauw @gesinn-it-gea are we ready to merge?

**Comment by kghbln** [comment]
proto docu at https://www.semantic-mediawiki.org/wiki/Help:Carousel_format

**Pull request merged**
