### PR TITLE
Updated fullcalendar and added list views

### PR DESCRIPTION
**Pull request by nischayn22**
This PR addresses or contains:
- Updated fullcalendar to the latest version. (FullCalendar v1.5.4 -> v3.9.0)
- Added [list views](https://fullcalendar.io/releases/fullcalendar/3.9.0/demos/list-views.html) to event calendar format

Fixes: #252

### CODE REVIEW

**Comment by mwjames** [comment]
Thanks but ...

... the changes from FullCalendar v1.5.4 -> v3.9.0 contains various API changes and causes the `eventcalendar` to function in some part incorrectly (verified manually!). I could request to have this fixed but then I'm guessing you'd abort the PR (as it happens the last time) therefore as an exception I'll merge the PR and will add a follow-up.

- themeSystem, eventSources (requires [ { } ]), defaultDate, onDayClick gets a Moment.js object instead of a date, extra buttons need to a group to be have the correct design etc.

**Comment by mwjames** [comment]
> Anyways, I think merging this is a huge step forward for this format. Could you please open a issue with steps to reproduce.

I merged the follow-up (#385) with changes now being available at [0]. If time permits try to give it a spin to see whether something else is missing or not.

[0] https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&cl=YzoljstuhDAMRb8G70CIEUsv-tCo63bRtScYiAjJyDZD5-9rBukuTuyb5Pxh3b97vkjrrr3TxNXlzfPNYROJefIpPzib1v2np-qu9eV6tgcyhrHISoavTqDEeSCBFNdo2LcOeUFKCWamgUVR57KDMkmYE904YdM0VdeOm9jM4iSsWzKFgUdyeETeMUW1nXmB46S4lmxz1X3cSGP49bnzUTkQxihqAz3xZ3OVJ6iRuB5JiqwGiSdXxFwyg_-4Mr5egZBiWLw6sZ1LLX4Nirg1kgYo46i-a2GlmE_1fw

**Comment by nischayn22** [comment]
listMonth doesn't work for me, see [0]. I think the last two replaces need to be inverted [1]

[0]https://goo.gl/9vXVzx
[1]https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/385/files#diff-89be5149c4980c6d7fd917570ed42848R85

**Comment by mwjames** [comment]
>  listMonth doesn't work for me, see [0]. I think the last two replaces need to be inverted [1]

Allowed values are `'values' =>  [ 'month', 'basicweek', 'basicday', 'agendaweek', 'agendaday', 'listday', 'listweek', 'listmonth' ]` which means `listMonth` is switched to `month` [0].

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/385/files#diff-607b55d2ae87a8789d503354fd74960fR52

**Comment by nischayn22** [comment]
Using "listmonth" doesn't work and "month" doesn't show the list view.
https://goo.gl/ATTMqE

**Comment by mwjames** [comment]
> Using "listmonth" doesn't work and "month" doesn't show the list view.

Changed to https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/681b4388e88d31983710f8b43eebc8cfb7d15919

**Comment by nischayn22** [comment]
I was just typing:
It does work if the views are in that order. "Month,listDay,listmonth,listweek" works but "listmonth,listweek,Month,listDay" doesn't.

I think your fix should work. I have updated the example here: https://sandbox.semantic-mediawiki.org/wiki/Issue/SRF/384

**Pull request merged**
