### PR TITLE
Fix class ref in slideshow API

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by s7eph4n** [comment]
Thanks, @JeroenDeDauw !

Looks good to me, but I do not have a test setup to verify. Suggest to merge and ask @jaideraf and/or @mitchelln to confirm the issue can be closed.

**Comment by JeroenDeDauw** [comment]
It's obvious enough the ref was broken and now is not

**Comment by jaideraf** [comment]
@s7eph4n I confirm: slideshow format works now.
@JeroenDeDauw: thanks for the fix.

**Comment by mitchelln** [comment]
I will also test, but is sounds like it has been resolved. Good work!

**Comment by mitchelln** [comment]
Confirmed fixed.

**Comment by JeroenDeDauw** [comment]
I tagged the rel earlier today, so you can do a composer update to get it

**Pull request merged**
