### PR TITLE
Graph format: Refactoring and enhancing

### PR DESCRIPTION
**Pull request by gesinn-it**
This PR is made in reference to: #

This PR addresses or contains:
- refactored, added SRFGraphNode class
- added handling for additional labels (label1 - label3)
- added record/Mrecord type shapes
- added arrowhead parameter
- added support for Display Title

This PR includes:
- [ ] Update of RELEASE-NOTES.md
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by gesinn-it** [comment]
... I'll add a screenhot soon to show, how this new label parameters can be used.

**Comment by gesinn-it** [comment]
Example Query:

```
{{#ask:[[Category:Team]][[Part Of Team::+]]
  |?Part Of Team
  |?Display Title=label1
  |?Casted Leadership Role=label2
  |?Casted=label3
  |format=graph
  |arrowhead=none
  |nodeshape=Mrecord
  |graphsize=20,20
  |graphcolor=no
  |graphlink=no
  |graphlabel=no
  |graphlegend=no
  |arrowdirection=BT
}}
```

**Comment by gesinn-it** [comment]
srf graph

In the top box, only label1 is used, in bottom left box, all three labels are used, in bottom right box, label1 and label3 are used (used means, that the query had results)

**Comment by gesinn-it** [comment]
“This PR has received funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 741782”.

**Comment by mwjames** [comment]
I'll be doing only a quick review given that my last comments on SFS went into thin air and I'm pressed with time during my support window.

> This PR has received funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 741782

Each PR should note the grant agreement so they can be easily distinguishable (given that those grants are created from tax payers money).

Here some initial comments without looking too much at the code itself:

- One class per file (see SRFGraphNode)
- Adding a new class -> requires a unit test
- SRF is namespaced, so newly or refactored classes should carry this characteristic
- PHP class properties don't require a prefix `m_` (see private $m_id;)
- Ensure explicit visibility ( `function __construct( $id ) {`)
- Why does the parameter name change from `srf-paramdesc-graphlegend` to `srf_paramdesc_graphlegend`? (In general we want a hyphen as separator, not an underscore)
- Why do we change from the `[ ... ]` to `array( ... )` as array declaration?

**Comment by gesinn-it** [comment]
@mwjames uups, obviously something went completely wrong with this PR. Seems that I accidentally merged a wrong branch of the code from our internal gitlab. Also my PHPStorm code formatter has messed up something. I'll double check. Sorry.

**Comment by gesinn-it** [comment]
@mwjames would you recommend moving the Graph format to an own directory (graph)? Currently it's sharing the graphviz directory with the Process format?

**Comment by gesinn-it** [comment]
@SchmidDev please do not update this PR with temp. stuff. @mwjames (and others) please ignore latest commits. The whole thing is a complete mess now.

**Comment by mwjames** [comment]
> would you recommend moving the Graph format to an own directory (graph)

Yes.

CI failures have been fixed with 9769c97.

**Comment by mwjames** [comment]
@gesinn-it  Are we going to continue this one, would be a shame if steam is running out here! 

By the way, I saw something peculiar, the naming of getLabel1, getLabel2, and getLabel3. Either use a more descriptive name or simply use `getLabel(...)` where it takes an argument and can generate any number of (maybe something like 4 or 5 in future) labels. Having 1,2,3 as name doesn't really appeal to me.

**Comment by gesinn-it** [comment]
@mwjames yes, we are definitely continue this one. I'm traveling the next two weeks (including SMWCon). I hope I can finish latest during SMWCon...

**Comment by mwjames** [comment]
#314 can guide you on the principles of how a refactoring effort can look like.

**Comment by gesinn-it** [comment]
@mwjames thanks for the hint with #314. I'll have a look at it. I continued this one but still a few things to clean up. Hope to have it ready before next weekend.

**Comment by gesinn-it** [comment]
> GraphNode
> 
> I couldn't see any `GraphNode` unit test (use the standard inheritance
> `PHPUnit_Framework_TestCase`)

> Each class is tested on its own which means `GraphNode` =>
> `GraphNodeTest` (avoid mingling otherwise it becomes some form of an
> integration test).

I'll create separate `GraphNodeTest.php` file

**Comment by gesinn-it** [comment]
> GraphResultPrinter
> 
> There are a lot of hard-coded strings like `$graphInput .=
> "[label=\"{" . $label;`, is it possible to isolated this in a more
> formalized and intelligent formatter class that only deals with the
> formatting and once done outputs the final string?

Good idea, I'll create a GraphFormatter class + GraphFormatterTest...

**Comment by s7eph4n** [comment]
Would it make sense to change the PSR-4 pointer in `composer.json` to the /formats/ directory instead of creating a /src/ directory for one format?

**Comment by mwjames** [comment]
> Would it make sense to change the PSR-4 pointer in `composer.json` to the
> /formats/ directory instead of creating a /src/ directory for one format?

Refactored formats should go into `/src` as what happened in #314.
This is to get some uniformity and have somewhat of a task list about
the once that are tested and those that contain "old" code.

There is no rush to make the switch and only the once that are truly
refactored should be moved to`/src`.

Cheers

**Comment by mwjames** [comment]
> Would it make sense to change the PSR-4 pointer in `composer.json` to the
> /formats/ directory instead of creating a /src/ directory for one format?

@s7eph4 Just a quick comment (since I don't have a ticket on this one)
as it touches the refactoring issue.

Currently, all resources are defined in `Resource.php` which becomes
rather "stuffed", so I was thinking what about an extra internal
setting to map the location of a format specific `Resource.php` and do
a `require_once` with the registration of a format?

```
$GLOBALS['srfgFormatResources'] = [
 formatYxz => location/Resource.php
]
```

Sorry, for hijacking this issue!

**Comment by s7eph4n** [comment]
One of my biggest problems when looking for something in the SMW code is that I never know, in which folder to start. Given the structural changes in SMW the "clean slate" approach makes sense, but I think SRF is already structured well enough and any new folder structure will look pretty much the same as the old one.

I would also challenge the other two points. Arranging the project structure to have a tasklist is somewhat similar to putting ToDos and FixMes in the code. If we want a task list we should use a Github issue/project/whatever. 

And test coverage or 'refactoring done' as a criterion to move formats to the new folder will probably not work either. I am working on the Filtered format right now. Done some refactoring, but it is still messy. Move over or not? Same goes probably for a number of other formats.

Finally with SRF we are in a situation, where usually a format is worked on when somebody has an issue with it. Given this approach we will end up having the `src` and `formats` folders side by side forever because some zombie formats will never get cleaned up.

So, I would suggest
1. Moving **all** formats to `src` (or what about `src/Formats`?)
2. Creating a Rework project on Github
3. If possible removing the unused, unmaintained formats

**Comment by mwjames** [comment]
Moving the discussion about refactoring in general to #321.

**Comment by mwjames** [comment]
> commented 11 days ago 

@gesinn-it Any update?

**Comment by mwjames** [comment]
This PR  is open since Aug 31, and we still have some unresolved issues. Do expect an update in near future?

**Comment by gesinn-it** [comment]
@mwjames: I'm very busy with projects at the moment. I will definitely need some days to do the changes you have suggested. No worries that this PR dies, because I need the changes to the graph format myself ;-)

**Comment by mwjames** [comment]
If this ever gets completed, please see #365.

**Comment by mwjames** [comment]
> @RacoonDev
manage invalid offset of label
c0afa5d 

Please make sure you use the master (see section "Conflicting files") as base, furthermore please DO NOT change the composer to something like:

> @RacoonDev
change semantic mediawiki version because of dependency problems
44fc73c 

Master works against master and against a restricted branch like "~2.5.3".

**Comment by mwjames** [comment]
@kghbln @hexmode @krabina @gesinn-it @RacoonDev This PR has been stuck here for nearly two years and I'm wondering whether we can resurrect this change and finalize it, otherwise we need to close it.

Also, as indicate above I expect that people committed to a PR do finalize it in an appropriate amount of time. Please consider this as a topic for discussion among yourself for the next SMWCon about how to improve contributions and what is needed to make them an actually contribution to the overall SMW community.

### Note

An epic task of refactoring should be split into smaller pieces making room for early adaptions without necessarily impairing existing functionality.

**Comment by mwjames** [comment]
As for "added support for Display Title" see #496 which was merged prior given the unknown state of this PR.

**Comment by gesinn-it** [comment]
@mwjames this PR really got stuck. Development progressed somewhat bumpy between branching 3.0 and general refactoring. In the meanwhile, the code base of SRF has evolved. I think we should consider closing this PR and re-implement on current code base... The gesinn.it team could do this job during the next weeks.

**Comment by mwjames** [comment]
> re-implement on current code base... The gesinn.it team could do this job
> during the next weeks.

I would appreciate that and maybe doing it in smaller iterative steps
might help to get this done where you use the current PR as blueprint
for the expected outcome.

**Comment by RacoonDev** [comment]
@JeroenDeDauw could you please close this PR. 
Thanks!

**Comment by kghbln** [comment]
> could you please close this PR.

Done

**Pull request closed without merging**
