### PR TITLE
Add CI for MW 1.41

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by paladox** [comment]
@gesinn-it-gea / @gesinn-it-ilm I'm not sure why phpunit is getting killed with this.

**Comment by paladox** [comment]
Seems it might be the integration tests?

**Comment by paladox** [comment]
Adding @group Database seemed to allow it to proceed.

**Comment by paladox** [comment]
Dunno why we're getting:

> Error: Class "SRF\Tests\ResultPrinterReflector" not found

now?

**Comment by paladox** [comment]
@gesinn-it-ilm any idea on a fix for it can't find the SRF\Tests\ResultPrinterReflector class? I can't seem to figure it out as we use addPsr4 in bootstrap and `$autoloader->addPsr4( 'SRF\\Tests\\', __DIR__ . '/phpunit' );` should basically pick it up. But we also have:

```
$autoloader->addClassMap( [
	'SRF\Tests\ResultPrinterReflector'             => __DIR__ . '/phpunit/ResultPrinterReflector.php',
] );
```

Really is strange.

**Comment by paladox** [comment]
Oh... using:

```
	"TestAutoloadNamespaces": {
		"SRF\\Tests\\": "tests/phpunit/"
	},
```

in extension.json fixed that.

**Comment by paladox** [comment]
@gesinn-it-ilm Maybe we need to move https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/Resources.php to extension.json? I dunno? Or change the check to check for if it's an array/string?

**Comment by paladox** [comment]
looks like that function was changed in https://github.com/wikimedia/mediawiki/commit/69ad795df7719a7854672140afa3a07269639978#diff-2bb9aed197663542c3ac9042287257d14a066acaf74d509ebee315022ca35022R338

**Comment by paladox** [comment]
Works now!

**Review by gesinn-it-ilm — APPROVED** [review]

**Comment by paladox** [comment]
@gesinn-it-ilm needs merging please :)

**Pull request merged**
