### PR TITLE
Update TagCloud.php

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #253 

This PR addresses or contains:
- Remove obsolete "div" element `align="justify"`

This PR includes:
- [x] Update of RELEASE-NOTES.md
- [ ] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
Note self: Needs to be backported to 2.5.x

**Comment by s7eph4n** [comment]
Needs testing. 😛 

No really, it has never been easier. Just specify a test setup and then use a CSS selector that expects not to see a certain attribute.

See [0] for an example test, [1], [2], [3] for some relevant CSS docu.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/6077519/tests/phpunit/Integration/JSONScript/TestCases/Filtered-01.json
[1] https://stackoverflow.com/questions/1533444/css-selector-to-match-an-element-without-attribute-x#1533485
[2] https://developer.mozilla.org/en-US/docs/Web/CSS/:not
[3] https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

**Comment by kghbln** [comment]
> No really

@s7eph4n This is part of a bigger issue. So far this result format is completely untested which needs to be changed. Testing for something not present should be part of it. I would like to move this to another issue rather than having this as holdup. In the end we are removing "functionality" ;)

**Comment by JeroenDeDauw** [comment]
@s7eph4n I'm not sure what you would test here. You can test that the CSS attribute is there or not, though that does not tell you anything about if it is doing the job it is supposed to be doing or not. So while tests for this format and stuff in general are cool, I don't think it makes sense to write any for this PR.

**Comment by JeroenDeDauw** [comment]
@kghbln not sure it's worth spending time on backporting a change like this one

**Comment by s7eph4n** [comment]
@JeroenDeDauw Well, the issue was that the `align` attribute is obsolete and should be removed. It was not that the output of the gallery format looks bad.
So I would test that that issue is indeed fixed, i.e. the attribute not present anymore. Although I agree that testing that something is not there anymore is really a special case test.

**Pull request merged**
