### PR TITLE
Fix typo in file jquery.blockUI.js

### PR DESCRIPTION
**Pull request by zoranzoki21**
Update typo supress -->> suppress in file jquery.blockUI.js

Part of fixing typos in code of SemanticMediaWiki and extensions for it tracked in task https://phabricator.wikimedia.org/T201491 at Wikimedia Phabricator.

### CODE REVIEW

**Comment by zoranzoki21** [comment]
@mwjames What happening with CI? Nothing not happening while building.

**Comment by zoranzoki21** [comment]
I will create new pull request with more files included.

**Comment by mwjames** [comment]
> @mwjames What happening with CI? Nothing not happening while building.

The CI on SRF is broken by [0].

For simple type changes, add the [skip ci] to the PR comments to avoid any issue in case only textual representations are altered.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/390#issuecomment-408658912

**Comment by zoranzoki21** [comment]
@mwjames Ok, thanks!

**Pull request closed without merging**
