### PR TITLE
Use layout instead of dom for datatables

### PR DESCRIPTION
**Pull request by alistair3149**
Follow up to #864

### CODE REVIEW

**Comment by thomas-topway-it** [comment]
@alistair3149 it seems really fine! Just a note: will `top9End` be placed on the right if `top9Start` is missing ?

**Comment by alistair3149** [comment]
@thomas-topway-it yes it will place on the end even if start is missing.
I put it there for now because I am not sure how it is used normally.

On a side note, do you have more example pages on how DataTables are being used currently in SMW?  I am planning to style the DataTables closer to the [Table component in Codex](https://doc.wikimedia.org/codex/main/components/demos/table.html), and it would be helpful to be able to take different layouts into consideration.

**Comment by thomas-topway-it** [comment]
I see Codex has improved a lot lately ...
regarding examples I have only this
https://www.semantic-mediawiki.org/wiki/Help:Datatables_format#Demos
this
https://starcitizen.tools/Gun
and this
https://wikincat.org/wiki/Form:Circulation

**Comment by jaideraf** [comment]
So, this is ready to be merged, right?

**Pull request merged**
