### PR TITLE
fix error when using intro and outro text

### PR DESCRIPTION
**Pull request by YvarRavy**
Fixes issue: https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/853
i first checked how SMW handels this with broadtable and pretty much just moved this code

### CODE REVIEW

**Comment by YvarRavy** [comment]
could you check this out? @gesinn-it-ilm

**Comment by gesinn-it-ilm** [comment]
@JeroenDeDauw could you please review this PR? Thanks.

**Comment by JeroenDeDauw** [comment]
Costs too many brain cycles. If another dev vouches for this code I am happy to merge

**Comment by thomas-topway-it** [comment]
I will check it soon on my side, I was also planning to do a few updates to carousel format

**Comment by thomas-topway-it** [comment]
I'm sorry for the delay. As pointed out [here](https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/853) the error shows when Datatables is called from the **Special:Ask** page and `$this->mOptions` are not set in the MW `Parser` (when `$this->parser->recursiveTagParseFully` is called from the function `handleNonFileResult`) 

Therefore

`$isValid = $this->parser->getOptions() && $this->parser->getTitle();`

as in `SMW\Parser\RecursiveTextProcessor` could be checked before using `$this->parser->recursiveTagParseFully` in order to set Parser's `setOptions` explicitly, or just to use the original solution (from `SMW\Query\ResultPrinters\ResultPrinter`) pointed out by you.

(I will merge it, then I will add a comment in the code with instructions to fix the original Datatables solution if needed)

**Review by thomas-topway-it — APPROVED** [review]
assessment & tested

**Pull request merged**
