### PR TITLE
Datatables v2

### PR DESCRIPTION
**Pull request by thomas-topway-it**
A complete refactoring of the datatables result format implementing a dedicated api and a SMW <code>BeforeQueryResultLookupComplete</code> hook in order to perform some preprocessing of the table data.

It includes the legacy datatables format with the format name <code>datatables-legacy</code>

Here is the complete documentation

https://www.semantic-mediawiki.org/wiki/Help:Datatables_format_(v2)

Key features:

- cells content fully consistent with the standard SMW table format (including the use of [Printouts format](https://www.semantic-mediawiki.org/wiki/Help:Displaying_information))
- can access all the rows of a query using Ajax when necessary
- supports navigation, filtering, and sorting against the complete data-set (using Ajax when necessary)
- supports [sorting](https://www.semantic-mediawiki.org/wiki/Help:Sorting) using multiple columns
- a wide range of native Datatables options are accessible through the askquery

### CODE REVIEW

**Comment by thomas-topway-it** [comment]
regarding the conflicts please note that some files have been renamed, for instance  <code>formats/datatables/DataTables.php</code> is now <code>formats/datatables-legacy/DataTables.php</code>

**Comment by JeroenDeDauw** [comment]
So this is a breaking change for users of the existing datatables format?

**Comment by JeroenDeDauw** [comment]
Needs rebase against master

**Comment by thomas-topway-it** [comment]
see here https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/771  
(created new branch based on the original repository, then merged this branch into the new branch)

**Pull request closed without merging**
