### PR TITLE
Start 3.0.0 development version

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #190 

This PR addresses or contains:
- Starts the development of SRF 3.0.0 on master since 2.5.x is now on its own branch

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by s7eph4n** [comment]
@kghbln, I just added a checkbox to the pull request template to update the release notes with every PR. I think this should help to minimize the effort to release new versions. It means however, that there should always be a section in the release notes for upcoming versions, where updates can be put.
What do you think? :wink:

**Comment by kghbln** [comment]
@s7eph4n 

> I just added a checkbox to the pull request template to update the release notes with every PR. I think this should help to minimize the effort to release new versions.

Great, good idear

> It means however, that there should always be a section in the release notes for upcoming versions, where updates can be put.

You mean link this: https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/ef955e0cb19baecfeb161842b088d1cc7edef19b :) I think in the past the first one with something started this but this indeed provides more guidance.

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/ef955e0cb19baecfeb161842b088d1cc7edef19b
> :) I think in the past the first one with something started this but this
> indeed provides more guidance.

If possible, I still like to see the back-ported sha1 otherwise if you
not link the #... number as reference it is difficult to find the
exact port.

**Comment by kghbln** [comment]
> If possible, I still like to see the back-ported sha1 otherwise if you not link the #... number as reference it is difficult to find the exact port.

Yeah, however the items are already in the list which will make it easier to identify and see what happened.

**Pull request merged**
