### PR TITLE
SemanticResultFormats (KM-A)

### PR DESCRIPTION
**Pull request by thomas-topway-it**
fix issue https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/724 (carousel not working)

### CODE REVIEW

**Comment by gesinn-it-gea** [comment]
To me this looks like the embedded jquery has been patched. This would break again on jquery update.

**Comment by krabina** [comment]
What is the alternative?

**Comment by gesinn-it-gea** [comment]
... well, the original source https://github.com/Wilto/Dynamic-Carousel isn't maintained anyway. So risk of breaking again is almost 0. An alternative would be to use an alternate plugin that is maintained while ideally keeping the SMW interface unchanged :-)

**Comment by krabina** [comment]
Yes, I see. Well then the scope of this PR is clear: to fix the bug when bootstrap is present. Maybe we should open another issue that SRF is using an outdated plugin.

**Comment by malberts** [comment]
I think this is fine (and rought what I had in mind in https://github.com/ProfessionalWiki/chameleon/issues/346#issuecomment-1249013722).

The upstream plugin is dead and if there happens to be an update there then the diff will at least show the name changed again and git blame should trace it back to this issue.

**Comment by gesinn-it-gea** [comment]
... if you look at the timestamps, most of the js has not been touched the last years. As long as they work, it's fine. But fixing security issues or keeping things running with more recent versions of other components is another story. Having an additional issue to follow-up on this one is definitely the right direction.

To my opinion, this PR can be merged to get your original problem solved.

**Comment by krabina** [comment]
#728

**Pull request merged**
