### PR TITLE
Update SRF_Array.php

### PR DESCRIPTION
**Pull request by kghbln**
This PR addresses or contains:
- Reuse system message provided by SMW
- Use existing system message provided by SRF

This PR includes:
- [ ] Update of RELEASE-NOTES.md
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
REM: Squash and merge

**Comment by JeroenDeDauw** [comment]
> Failed asserting that false is true.

Seems like your PR broke boolean logic!

**Comment by kghbln** [comment]
> Seems like your PR broke boolean logic! Nowait, given the message, it must have fixed it...

No, it was not me. It was twn if you look at the latest code changes. :)

**Comment by mwjames** [comment]
> No, it was not me.

Test failures were due to #309.

**Comment by kghbln** [comment]
> Test failures were due to #309.

But this does not seem to be a holdup for a merge?

**Comment by JeroenDeDauw** [comment]
Now that the tests passed things are fluff.

**Comment by kghbln** [comment]
Squash and merge is nicer since it will also allow for easier back-porting.

**Pull request merged**
