### PR TITLE
Gallery format: fix default= setting

### PR DESCRIPTION
**Pull request by krabina**
This PR is made in reference to: #396 

This PR addresses or contains:

new private function getNumbers
call to function right after getResultText
function addNumbersForDataItem (was missing pn previous PR)

Sorry for my unprofessional pull request :-)

This PR includes:
- [ ] Update of RELEASE-NOTES.md
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #

### CODE REVIEW

**Comment by krabina** [comment]
i copied the code from math result, by the way

**Comment by s7eph4n** [comment]
I don't understand the logic of this PR. How is it supposed to work?
And there is a relevant test failing (see travis), so either this patch does not do what it should, or the test needs fixing.

**Comment by krabina** [comment]
sorry about that. as I said I copied code from the math result format. it works in my wiki, but I did not test it professionally. thought it must be an easy fix as it works in the other result formats. Feel free to just delete it.

**Comment by kghbln** [comment]
@krabina I guess this pull can be closed?

**Comment by krabina** [comment]
I guess so

**Comment by kghbln** [comment]
> I guess so

Happened to me too. Trying to imitate something existing because it seemingly looks identical in a way and end up in a ball of issues because things are not similar at all. To cut it short: I feel with you.

**Pull request closed without merging**
