### PR TITLE
Filtered:  Fix value filter labels. Fix QUnit tests for MW 1.31+

### PR DESCRIPTION
**Pull request by s7eph4n**
This PR is made in reference to: #354, https://phabricator.wikimedia.org/T170515

This PR addresses or contains:
- Fix value filter labels.
- Fix QUnit tests for MW 1.31+

This PR includes:
- [ ] Update of RELEASE-NOTES.md
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by s7eph4n** [comment]
Travis CI testing is broken for the moment because the latest version of Composer 1.5.3 fails (see https://github.com/composer/composer/issues/6860) and there are reports that 1.5.4 used by us did not fix this either.
I'll merge this PR in spite of the failing Travis tests because the CI tests run locally and the PR does not touch PHP anyway.

**Comment by gesinn-it** [comment]
will this be backported to 2.5.x branch?

**Comment by s7eph4n** [comment]
Can do.

**Comment by s7eph4n** [comment]
See #360

**Pull request merged**
