### PR TITLE
Prolog and R dataframe formats

### PR DESCRIPTION
**Pull request by mfalda**
This PR is made in reference to: #9914a7628e9b74cfd35d8a7d07fbffaad9d21241

This PR addresses or contains:
- a new Prolog printer format that generates SVO predicates.
- an R dataframe printer format for exporting dataframes.

This PR includes:
- [ ] Update of RELEASE-NOTES.md
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #

### CODE REVIEW

**Comment by krabina** [comment]
@gesinn-it-gea or @JeroenDeDauw is this ready for being accepted?

**Comment by krabina** [comment]
Can we accept this? @JeroenDeDauw @gesinn-it-gea 
It is a great idea to have an R result format!

**Comment by JeroenDeDauw** [comment]
This PR was marked as draft by OP, so IDK if it is even finished

**Comment by krabina** [comment]
Ah I see. @mfalda is this working well for you?

**Comment by mfalda** [comment]
I developed these SRF for a scientific paper just submitted for review. At the end I used only the Prolog predicates idea for another repository [smw SWI- Prolog pack](https://github.com/mfalda/smw/), since a colleague told me that data scientists usually create dataframes form plain data formats (that is CSV files). In fact, also Prolog predicates could be created from CSV, but I like them more as predicates.
Hopefully, it will be all clearer if the paper will be published ...

I left the pull request in draft since tests are still missing. I do not think that I will develop further the R dataframe format, but in my opinion the possibility to connect from Prolog would be nice.

**Comment by mfalda** [comment]
In any case, I can remove the "draft" status in the case someone wants to integrate the code.

**Comment by krabina** [comment]
Great, thank you for the info, good luck for your paper and we hope you stay on board. Please submit a short presentation at SMWCon: https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2022
As it is not an academic conference, you cannot talk about your paper before it is published, but you could certainly give a short talk about the two new formats in your PR.

**Comment by mfalda** [comment]
Thank you. I will try to work on a simple example in Prolog and/or R and,
if worth, I will propose a brief talk.


Il mar 20 set 2022, 10:36 Bernhard Krabina ***@***.***> ha
scritto:

**Comment by krabina** [comment]
@mfalda sorry your brief talk did not happen. Anyway, can you provide us with a simple example so we can test this. I would like to see this integrated.

**Comment by krabina** [comment]
The link points to a closed wiki.

**Comment by mfalda** [comment]
I am sorry, I forgot to specify the credentials!
You can login with Username = Test and password = eest   .

**Comment by krabina** [comment]
Can you update your branch? Then I guess there are no conflicts anymore.

**Pull request merged**
