### PR TITLE
Add hidezeroes parameter to jqplotseries

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/558

Untested. Needs at least a manual test before merge.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@darenwelsh could you do a manual test?

**Comment by darenwelsh** [comment]
Thanks! Yes, I will test this. It will be a few days before I get to it.

**Comment by darenwelsh** [comment]
It looks like you added a parameter "hidezeroes". Is this configured in-wiki, as a parameter in the ask query? Or is this a parameter configured per-wiki in LocalSettings.php?

**Comment by kghbln** [comment]
Looks very much like a parameter to the result format which you can use when specifying the result output of the respective inline query like e.g. charttitle, charttext, etc.

**Comment by darenwelsh** [comment]
I added `|hidezeroes=true` to the ask query and it worked (it hid the zeroes). I removed that parameter and the zeroes show up (by default). So I think it works :)

image

**Comment by kghbln** [comment]
> I added |hidezeroes=true to the ask query and it worked (it hid the zeroes). I removed that parameter and the zeroes show up (by default). So I think it works :)

Great. Thanks for the successful test. :) Will merge this now.

**Comment by JeroenDeDauw** [comment]
In release notes with 98fcb73d694e81d744c9047bdc004464bc064e12

**Comment by JeroenDeDauw** [comment]
@darenwelsh you could do a thank you tweet mentioning @ProWikiExperts since you already have an image you can stuff in there. (Sorry, full advertising mode Jeroen here :))

**Comment by darenwelsh** [comment]
Will you be joining us at EMWCon in April? I'll buy you a beer!

**Comment by JeroenDeDauw** [comment]
I hope to be at the next EU conference.

**Pull request merged**
